DROP TABLE artista IF EXISTS;
DROP TABLE album IF EXISTS;
DROP TABLE regional IF EXISTS;

CREATE TABLE usuario (
     id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     username VARCHAR(30),
     senha VARCHAR(10)
);

CREATE TABLE artista (
      id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nome_artista VARCHAR(30),
      data_atualizacao DATE,
      ativo VARCHAR(1)
);

CREATE INDEX artista_nome ON artista (nome_artista);

CREATE TABLE album (
     id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     id_artista INTEGER NOT NULL,
     nome_album VARCHAR(80),
     data_atualizacao DATE,
     ativo VARCHAR(1)
);
CREATE INDEX album_nome ON album (nome_album);

ALTER TABLE album ADD CONSTRAINT fk_album_artista FOREIGN KEY (id_artista) REFERENCES artista (id);

CREATE TABLE regional (
       id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       nome VARCHAR(80),
       ativo VARCHAR(1)
);
CREATE INDEX regional_nome ON regional (nome);
